#!/bin/bash

db_name='states'

make data/raw/results.txt

dropdb --interactive --if-exist $db_name
createdb $db_name

psql -f sql/schema.sql $db_name

read -r -d '' create_sql <<'EOF'
COPY elections
FROM STDIN
WITH CSV HEADER
DELIMITER E'\t'
ESCAPE E'\\'
EOF

cat data/raw/results.txt | psql -d $db_name -c "$create_sql"
